### ISSUE TITLE
How to remove first delay transition?

### ISSUE THREAD

**Issue by tonicastillo** [ryanwiemer/gatsby-using-page-transitions#1]
Hi! 👋
(please, excuse my english)
I'm using your example, great btw, for one of my projects and I have an issue. When load the page, the first transition, there is a delay before animation starts. I edited your code and changed duration from 0.5 to 3, so you can see the problem with long start animations.

![Example](https://4d-share.s3-eu-west-1.amazonaws.com/gatsby-using-page-transitions%20example.gif)

Do you know how to remove this delay?

Thanks!

**Comment by ryanwiemer** [comment]
@tonicastillo, 

That delay is intentional. The delay is set for whenever a page "enters" either via a route change or when it is first mounted. 

If you don't want any fade in transition on mount I believe you can set `initial={false}` on `AnimatePresence` on [Layout.js](https://github.com/ryanwiemer/gatsby-using-page-transitions/blob/master/src/components/Layout.js#L40). I haven't tested it out but you can give that a shot. 

Documentation on `AnimatePresence` can be found here: https://www.framer.com/api/motion/animate-presence/

**Comment by tonicastillo** [comment]
Hi @ryanwiemer 
I understand it's intentional.
I have tested adding initial = false to AnimatePresence, but this disable the animation, not only the delay.

I'll try another option. Thanks for your answer anyway.
